export default {
    startTimestamp: localStorage['startTimestamp'] || new Date().getTime(),
    choosenOperations: (localStorage['choosenOperations'] || '').split(',') || [],
    minComplexity: localStorage['minComplexity'] || 1,
    maxComplexity: localStorage['maxComplexity'] || 5,
    complexity: localStorage['complexity'] || 3,
    minTime: localStorage['minTime'] || 1,
    maxTime: localStorage['maxTime'] || 5,
    timeValue: localStorage['timeValue'] || 3,
    value1: localStorage['value1'] || 0,
    value2: localStorage['value2'] || 0,
    result: localStorage['result'] || 0,
    operation: localStorage['operation'] || '?',
    globalRights: localStorage['globalRights'] || 0,
    globalWrongs: localStorage['globalWrongs'] || 0,
    rights: localStorage['rights'] || 0,
    wrongs: localStorage['wrongs'] || 0,
    counter: localStorage['counter'] || 0,
    on: localStorage['on'] || false,
    finished: localStorage['finished'] || true,
}
